# Generated by Django 3.2.13 on 2022-08-04 15:24

import django.core.validators
from django.db import migrations, models
import jobs.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cpep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('peptide_name', models.CharField(max_length=100)),
                ('protein_chain_name', models.CharField(max_length=100)),
                ('receptor_chain_name', models.CharField(max_length=100)),
                ('pdb', models.FileField(null=True, upload_to='', validators=[jobs.validators.validate_file])),
                ('cutoff', models.FloatField(blank=True, default=7.0)),
                ('treshold', models.FloatField(blank=True, default=0.7)),
                ('motif', models.IntegerField(blank=True, default=4, validators=[django.core.validators.MaxValueValidator(7), django.core.validators.MinValueValidator(4)])),
            ],
        ),
        migrations.CreateModel(
            name='rsremd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('protein_complex_name', models.CharField(max_length=100)),
                ('receptor_chain_end', models.IntegerField(default=89)),
                ('ligand_chain_end', models.IntegerField(default=185)),
                ('pdb', models.FileField(null=True, upload_to='', validators=[jobs.validators.validate_file])),
            ],
        ),
    ]
