# Generated by Django 3.2.13 on 2022-10-25 12:25

from django.db import migrations, models
import jobs.models
import jobs.validators


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cpep',
            name='pdb',
            field=models.FileField(null=True, upload_to=jobs.models.user_directory_path, validators=[jobs.validators.validate_file]),
        ),
        migrations.AlterField(
            model_name='rsremd',
            name='pdb',
            field=models.FileField(null=True, upload_to=jobs.models.user_directory_path, validators=[jobs.validators.validate_file]),
        ),
    ]
