# Generated by Django 3.2.13 on 2023-11-25 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20221025_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='cpep',
            name='residue_numbers',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cpep',
            name='target_hotspots',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
