# Generated by Django 3.2.13 on 2023-11-30 03:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_auto_20231126_0314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cpep',
            name='treshold',
            field=models.FloatField(blank=True, default=0.7, validators=[django.core.validators.MaxValueValidator(2.5), django.core.validators.MinValueValidator(0.3)]),
        ),
    ]
